export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  VNPAY = 'VNPAY',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
}

export enum PaymentReviewReason {
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  ANOTHER_SUCCESSFUL_PAYMENT = 'ANOTHER_SUCCESSFUL_PAYMENT',
}
