export const ErrorCode = {
  COMMON_VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
  COMMON_UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_RATE_LIMITED: 'COMMON_RATE_LIMITED',
  COMMON_PAYLOAD_TOO_LARGE: 'COMMON_PAYLOAD_TOO_LARGE',
  COMMON_UNSUPPORTED_MEDIA_TYPE: 'COMMON_UNSUPPORTED_MEDIA_TYPE',
  COMMON_SERVICE_UNAVAILABLE: 'COMMON_SERVICE_UNAVAILABLE',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
  CUSTOMER_INITIAL_PASSWORD_ALREADY_CONFIGURED:
    'CUSTOMER_INITIAL_PASSWORD_ALREADY_CONFIGURED',
  CUSTOMER_EMAIL_IN_USE: 'CUSTOMER_EMAIL_IN_USE',
  CUSTOMER_PHONE_IN_USE: 'CUSTOMER_PHONE_IN_USE',
  CUSTOMER_CURRENT_PASSWORD_INVALID: 'CUSTOMER_CURRENT_PASSWORD_INVALID',
  CUSTOMER_PASSWORD_REUSE_NOT_ALLOWED: 'CUSTOMER_PASSWORD_REUSE_NOT_ALLOWED',
  AMENITY_NAME_ALREADY_EXISTS: 'AMENITY_NAME_ALREADY_EXISTS',
  AMENITY_IN_USE: 'AMENITY_IN_USE',
  ROOM_TYPE_IN_USE: 'ROOM_TYPE_IN_USE',
  BOOKING_GUEST_CAPACITY_EXCEEDED: 'BOOKING_GUEST_CAPACITY_EXCEEDED',
  BOOKING_CUSTOMER_CONTACT_REQUIRED: 'BOOKING_CUSTOMER_CONTACT_REQUIRED',
  BOOKING_ACTIVE_UNPAID_LIMIT_REACHED: 'BOOKING_ACTIVE_UNPAID_LIMIT_REACHED',
  BOOKING_HELD_NIGHTS_LIMIT_REACHED: 'BOOKING_HELD_NIGHTS_LIMIT_REACHED',
  BOOKING_ROOM_NOT_BOOKABLE: 'BOOKING_ROOM_NOT_BOOKABLE',
  BOOKING_CHECKIN_IN_PAST: 'BOOKING_CHECKIN_IN_PAST',
  BOOKING_CHECKIN_TOO_FAR: 'BOOKING_CHECKIN_TOO_FAR',
  BOOKING_DATE_RANGE_INVALID: 'BOOKING_DATE_RANGE_INVALID',
  BOOKING_STAY_TOO_LONG: 'BOOKING_STAY_TOO_LONG',
  BOOKING_TOTAL_LIMIT_EXCEEDED: 'BOOKING_TOTAL_LIMIT_EXCEEDED',
  BOOKING_ROOM_UNAVAILABLE: 'BOOKING_ROOM_UNAVAILABLE',
  BOOKING_CREATE_CONFLICT: 'BOOKING_CREATE_CONFLICT',
  BOOKING_CANCELLATION_REASON_REQUIRED: 'BOOKING_CANCELLATION_REASON_REQUIRED',
  BOOKING_REFUND_PENDING: 'BOOKING_REFUND_PENDING',
  BOOKING_TRANSITION_NOT_ALLOWED: 'BOOKING_TRANSITION_NOT_ALLOWED',
  BOOKING_CONFIRMATION_REQUIRES_PAYMENT:
    'BOOKING_CONFIRMATION_REQUIRES_PAYMENT',
  BOOKING_CHECKIN_REQUIRES_PAYMENT: 'BOOKING_CHECKIN_REQUIRES_PAYMENT',
  BOOKING_CHECKIN_OUTSIDE_STAY_WINDOW: 'BOOKING_CHECKIN_OUTSIDE_STAY_WINDOW',
  BOOKING_ROOM_NOT_FOUND: 'BOOKING_ROOM_NOT_FOUND',
  BOOKING_ROOM_MISSING_FOR_BOOKING: 'BOOKING_ROOM_MISSING_FOR_BOOKING',
  BOOKING_ROOM_NOT_READY: 'BOOKING_ROOM_NOT_READY',
  BOOKING_CANCELLATION_ALREADY_PAID: 'BOOKING_CANCELLATION_ALREADY_PAID',
  BOOKING_CANCELLATION_NOT_ALLOWED: 'BOOKING_CANCELLATION_NOT_ALLOWED',
  PAYMENT_REFUND_REJECTED: 'PAYMENT_REFUND_REJECTED',
  PAYMENT_REFUND_NOT_ALLOWED: 'PAYMENT_REFUND_NOT_ALLOWED',
  PAYMENT_REFUND_OUTCOME_UNKNOWN: 'PAYMENT_REFUND_OUTCOME_UNKNOWN',
  PAYMENT_IDEMPOTENCY_KEY_CONFLICT: 'PAYMENT_IDEMPOTENCY_KEY_CONFLICT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

const ERROR_CODES = new Set<string>(Object.values(ErrorCode));

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && ERROR_CODES.has(value);
}
